<?php
namespace backend\models;

use Yii;

/**
 * This is the model class for table "game_cmd".
 *
 * @property integer $id
 * @property string $cmd
 * @property string $name
 * @property string $p1
 * @property string $p2
 * @property string $p3
 * @property string $p4
 * @property string $p5
 * @property string $p6
 * @property string $p7
 * @property string $p8
 * @property string $p9
 * @property string $p10
 * @property string $f1
 * @property string $f2
 * @property string $f3
 * @property string $f4
 * @property string $f5
 * @property string $f6
 * @property string $f7
 * @property string $f8
 * @property string $f9
 * @property string $f10
 * @property string $notes
 * @property string $record_time
 */
class GameCmd extends \backend\models\BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'game_cmd';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cmd'], 'required'],
            [['record_time'], 'safe'],
            [['cmd','name'], 'string', 'max' => 64],
            [['settings'], 'string'],
            [['notes'], 'string', 'max' => 255],
            [['cmd'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cmd' => '指令',
            'name' => '指令名',
            'settings' => '配置',
            'notes' => '备注',
            'record_time' => '记录时间',
        ];
    }

  /**
     * 返回数据库字段信息，仅在生成CRUD时使用，如不需要生成CRUD，请注释或删除该getTableColumnInfo()代码
     * COLUMN_COMMENT可用key如下:
     * label - 显示的label
     * inputType 控件类型, 暂时只支持text,hidden  // select,checkbox,radio,file,password,
     * isEdit   是否允许编辑，如果允许编辑将在添加和修改时输入
     * isSearch 是否允许搜索
     * isDisplay 是否在列表中显示
     * isOrder 是否排序
     * udc - udc code，inputtype为select,checkbox,radio三个值时用到。
     * 特别字段：
     * id：主键。必须含有主键，统一都是id
     * create_date: 创建时间。生成的代码自动赋值
     * update_date: 修改时间。生成的代码自动赋值
     */
    public function getTableColumnInfo(){
        return array(
        'id' => array(
                        'name' => 'id',
                        'allowNull' => false,
//                         'autoIncrement' => true,
//                         'comment' => '',
//                         'dbType' => "int(10) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => true,
                        'phpType' => 'integer',
                        'precision' => '10',
                        'scale' => '',
                        'size' => '10',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('id'),
                        'inputType' => 'hidden',
                        'isEdit' => true,
                        'isSearch' => true,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'cmd' => array(
                        'name' => 'cmd',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '指令',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('cmd'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => true,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p1' => array(
                        'name' => 'p1',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数1',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p1'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p2' => array(
                        'name' => 'p2',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数2',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p2'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p3' => array(
                        'name' => 'p3',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数3',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p3'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p4' => array(
                        'name' => 'p4',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数4',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p4'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p5' => array(
                        'name' => 'p5',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数5',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p5'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p6' => array(
                        'name' => 'p6',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数6',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p6'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p7' => array(
                        'name' => 'p7',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数7',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p7'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p8' => array(
                        'name' => 'p8',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数8',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p8'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p9' => array(
                        'name' => 'p9',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数9',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p9'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'p10' => array(
                        'name' => 'p10',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数10',
//                         'dbType' => "char(64)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '64',
                        'scale' => '',
                        'size' => '64',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('p10'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f1' => array(
                        'name' => 'f1',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数1格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f1'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f2' => array(
                        'name' => 'f2',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数2格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f2'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f3' => array(
                        'name' => 'f3',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数3格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f3'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f4' => array(
                        'name' => 'f4',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数4格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f4'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f5' => array(
                        'name' => 'f5',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数5格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f5'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f6' => array(
                        'name' => 'f6',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数6格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f6'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f7' => array(
                        'name' => 'f7',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数7格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f7'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f8' => array(
                        'name' => 'f8',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数8格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f8'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f9' => array(
                        'name' => 'f9',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数9格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f9'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'f10' => array(
                        'name' => 'f10',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '参数10格式',
//                         'dbType' => "char(16)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '16',
                        'scale' => '',
                        'size' => '16',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('f10'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => false,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'notes' => array(
                        'name' => 'notes',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '备注',
//                         'dbType' => "char(255)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '255',
                        'scale' => '',
                        'size' => '255',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('notes'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'record_time' => array(
                        'name' => 'record_time',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '记录时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('record_time'),
                        'inputType' => 'text',
                        'isEdit' => false,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		        );
        
    }
 
}
